### ISSUE TITLE
Bug: short subdomain length stops frontend loading

### ISSUE THREAD

**Issue by Hiumee** [adrgs/requestrepo#43]
A short subdomain length will treat the `/static` path as a subdomain
The `get_subdomain_from_path` function usually returns `None` due to the `/` after those paths. With a subdomain length <= 6 the `/` character is not considered and passes the `set(subdomain) - alphabet_set != set()` check

**Comment by adrgs** [comment]
Good catch, thanks. Added `public` and `api` to `reserved_keywords` in `config.py`, such that they won't be overriden in the default case.
Fixed in #45

**Comment by Hiumee** [comment]
Still not fixed. `static` should be a keyword, other paths are affected like `logo.svg`
For a 4-letter domain, the line `subdomain = path[:length]` truncates the input from `static` to `stat` and fails the check
Something like `subdomain = path[:subdomain.find('/')]` when it contains `/` might be a better fix

**Comment by adrgs** [comment]
You're correct, it's `static` not public. Added it and a few others like `logo`, `assets` and `favicon` to keywords. I think that should be all.
Let me know if there's anything that I've missed in #49
